CREATE TABLE Supplier (
	cnpj VARCHAR(11) NOT NULL,
	name VARCHAR(50) NOT NULL,
	last_buy TIMESTAMP NOT NULL,
	quality_rate  VARCHAR(50) NOT NULL,
	probability_of_new_deals  VARCHAR(50) NOT NULL,
	CONSTRAINT Supplier_pk PRIMARY KEY (CNPJ)
);

CREATE TABLE Auditing (
	IDENTIFIER SERIAL NOT NULL,
	REGISTER_CODE NUMERIC(20) NOT NULL,
	DATETIME TIMESTAMP NOT NULL,
	CONSTRAINT auditing_pk PRIMARY KEY (IDENTIFIER),
	FOREIGN KEY (REGISTER_CNPJ) REFERENCES Supplier (CNPJ)
);

